name: Product Added Event Model
source: snowflake
description: LuLuLemon Demo
type: raw_sql
rawSql: |-
  SELECT
      EVENT_ID as id,
      CUSTOMER_ID as user_id,
      ANONYMOUS_ID as anonymous_id,
      TIMESTAMP as timestamp,
      'Product Added' as event_name,
      SESSION_ID as session_id,
      DEVICE_TYPE as device_type,
      BROWSER as browser,
      PROPERTIES:product_id::VARCHAR as product_id,
      PROPERTIES:product_name::VARCHAR as product_name,
      PROPERTIES:category::VARCHAR as category,
      PROPERTIES:price::FLOAT as price,
      PROPERTIES:quantity::INT as quantity
  FROM LULULEMON_EVENTS
  WHERE EVENT_TYPE = 'add_to_cart'
primaryKey: USER_ID
